trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: '1.3.6'
  resourceGroup: 'hari_check1'
  environment: 'prod'
  webapp_name: 'webapp$(env)'
  sql_name: 'sql$(env)'

stages:
- build
- deploy

build:
  stage: build
  displayName: 'Build'
  jobs:
  - job: build
    displayName: 'Build'
    steps:
    - task: TerraformInstaller@2
      displayName: 'Install Terraform $(terraformVersion)'
      inputs:
        terraformVersion: '$(terraformVersion)'
    - task: TerraformTaskV2@2
      displayName: 'Initialize'
      inputs:
        command: 'init'
        workingDirectory: './'
        environmentServiceName: ''
    - task: TerraformTaskV2@2
      displayName: 'Validate'
      inputs:
        command: 'validate'
        workingDirectory: './'
        environmentServiceName: ''
    - task: TerraformTaskV2@2
      displayName: 'Plan'
      inputs:
        command: 'plan'
        workingDirectory: './'
        environmentServiceName: ''
        arguments: '-var resource_group=$(resourceGroup) -var webapp_name=$(webapp_name) -var sql_name=$(sql_name)'
    - task: PowerShell@2
      displayName: 'Save Plan Output'
      inputs:
        targetType: 'inline'
        script: 'terraform show -no-color > terraform.plan'
    - task: UploadArtifact@2
      displayName: 'Upload Artifact'
      inputs:
        artifactName: '$(environment)-plan'
        paths: 'terraform.plan'

deploy:
  stage: deploy
  displayName: 'Deploy'
  dependsOn: build
  jobs:
  - deployment: deploy
    displayName: 'Deploy'
    environment: '$(environment)'
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadArtifact@2
            displayName: 'Download Artifact'
            inputs:
              artifactName: '$(environment)-plan'
              downloadPath: './'
          - task: TerraformInstaller@2
            displayName: 'Install Terraform $(terraformVersion)'
            inputs:
              terraformVersion: '$(terraformVersion)'
          - task: TerraformTaskV2@2
            displayName: 'Apply'
            inputs:
              command: 'apply'
              workingDirectory: './'
              environmentServiceName: ''
              arguments: '-var resource_group=$(resourceGroup) -var webapp_name=$(webapp_name) -var sql_name=$(sql_name) -auto-approve'
          - task: PowerShell@2
            displayName: 'Save State'
            inputs:
              targetType: 'inline'
              script: 'terraform show -no-color > terraform.state'
          - task: UploadArtifact@2
            displayName: 'Upload State'
            inputs:
              artifactName: '$(environment)-state'
              paths: 'terraform.state'