trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroup: 'hari_check1'
  appName: 'webapp'
  repositoryName: 'Simple_Insurance_portal'
  azureSubscription: 'your_azure_subscription'
  terraformVersion: '1.2.5'
  environment: 'production'

stages:
- build
- deploy

build:
  stage: build
  displayName: 'Build'
  jobs:
  - job: build
    displayName: 'Build'
    steps:
    - task: TerraformInstaller@2
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: '$(terraformVersion)'
    - task: TerraformTaskV2@2
      displayName: 'Initialize Terraform'
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
        environmentServiceName: '$(azureSubscription)'
    - task: TerraformTaskV2@2
      displayName: 'Validate Terraform'
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
        environmentServiceName: '$(azureSubscription)'
    - task: TerraformTaskV2@2
      displayName: 'Plan Terraform'
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
        environmentServiceName: '$(azureSubscription)'
    - task: CopyFiles@2
      displayName: 'Copy Terraform Plan'
      inputs:
        contents: '**/terraform.tfplan'
        targetFolder: '$(build.artifactstagingdirectory)/infrastructure'
    - task: PublishBuildArtifact@2
      displayName: 'Publish Artifact'
      inputs:
        artifactName: 'infrastructure'
        path: '$(build.artifactstagingdirectory)/infrastructure'

deploy:
  stage: deploy
  displayName: 'Deploy'
  dependsOn: build
  jobs:
  - deployment: deploy
    displayName: 'Deploy'
    environment: '$(environment)'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifact@2
            displayName: 'Download Artifact'
            inputs:
              artifactName: 'infrastructure'
              downloadPath: '$(System.DefaultWorkingDirectory)/infrastructure'
          - task: TerraformInstaller@2
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: '$(terraformVersion)'
          - task: TerraformTaskV2@2
            displayName: 'Apply Terraform'
            inputs:
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/infrastructure'
              environmentServiceName: '$(azureSubscription)'
              commandOptions: '-auto-approve'
          - task: AzureCLI@2
            displayName: 'Azure CLI'
            inputs:
              azureSubscription: '$(azureSubscription)'
              script: |
                az webapp deployment slot create --resource-group $(resourceGroup) --name $(appName) --slot production
              displayName: 'Create Deployment Slot'